### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by Doug-AWS** [awsdocs/aws-go-developer-guide#13]
Are there any services you would like to see examples in Go? Or more examples? Or a specific use case?

How about a multi-service example? Any ideas?

**Comment by CoolHandDev** [comment]
May we please get examples of using AWS Cognito with Go?  

Use cases:

1. Using Cognito to protect an API
2. Using Cognito as authentication for a command line app/tool

Thank you.

**Comment by Doug-AWS** [comment]
Will do. Probably won't happen until late in the year as re:Invent is looming.

**Comment by nfuhs** [comment]
Is it possible to get a free 12-month AWS account? If so I would like to help with this issue but I don't have a credit card which pretends me from register an AWS account.

**Comment by ghost** [comment]
Hi,
I  currently write Alexa skills with Go an would like to blog a tutorial about it. Is its possible to get in contact with Amazon which developer tutorials for Go developers are missing?

**Comment by Doug-AWS** [comment]
@nfuhs All of the Go examples are in the developer guide, https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/common-examples.html. The README.rst file at the root of the repo explains how we take PRs.

As far as I know there is no set path to support a third-party blog post on our AWS site. You might consider one of the many web sites where developers post how-to articles. I cannot give any recommendations for any specific sites.

I can help review your code and instructions if you want to put them where I can access them.

**Comment by ghost** [comment]
Thanks for the quick answer @Doug-AWS currently I work with other on a port of [https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs) for Go if you would like to help us with code reviews and hints that would be great. I will write a blog post about using it when it's done I already have contact with a developer blog so that should be no problem.

The repo is here but there will be a lot of change in the future:

[https://github.com/nfuhs/skill-sample-go-fact](https://github.com/nfuhs/skill-sample-go-fact)

**Comment by Doug-AWS** [comment]
You have a typo in your link to the Alexa skill sample for node.js. I filed a PR to fix it.

**Comment by Doug-AWS** [comment]
We are in the midst of re-leveling writer assignments, so I'm moving this to our backlog.

**Comment by ghost** [comment]
Closing this issue, as it has been open for over a year, and we already received feedback. 

Paul
AWS Documentation
